# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'loupan' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'JSONKit-NoWarning'
end

